package org.wit.beachapp.activities

import android.app.Activity
import android.content.Intent
import android.net.Uri
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import com.google.android.material.snackbar.Snackbar
import org.wit.beachapp.main.MainApp
import org.wit.beachapp.models.BeachModel
import org.wit.beachapp.R
import android.view.Menu
import android.view.MenuItem
import android.view.View
import android.widget.*
import androidx.activity.result.ActivityResultLauncher
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AppCompatDelegate
import androidx.lifecycle.MutableLiveData
import com.squareup.picasso.Picasso
import org.wit.beachapp.databinding.ActivityBeachBinding
import org.wit.beachapp.helpers.showImagePicker
import org.wit.beachapp.models.Location
import timber.log.Timber.i

class BeachActivity : AppCompatActivity(), AdapterView.OnItemSelectedListener {
    //Using autogenerated class to access view objects of the layout.
    private lateinit var binding: ActivityBeachBinding
    //Creating a beach as a class member of BeachModel()
    var beach = BeachModel()
    //Retrieving and storing reference to MainApp object where Beach list is.
    lateinit var app: MainApp
    //Launch image activity
    private lateinit var imageIntentLauncher : ActivityResultLauncher<Intent>
    //Launch map activity
    private lateinit var mapIntentLauncher : ActivityResultLauncher<Intent>
    var edit = false
    var walk = arrayOf<String?>("Has walking area", "No walking area")
    var visited = arrayOf<String?>("Visited", "To Visit")
    var dogs = arrayOf<String?>("Dogs allowed", "Dogs banned")
    var fishing = arrayOf<String?>("Fishing Beach", "No Fishing")


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        //Inflate layout
        binding = ActivityBeachBinding.inflate(layoutInflater)
        setContentView(binding.root)
        //Enable tool bar
        binding.toolbarAdd.title = title
        setSupportActionBar(binding.toolbarAdd)
        //Event handling - Add walk. Take the instance of Spinner and apply OnItemSelectedListener on it which tells which item of spinner is clicked
        val spin = findViewById<Spinner>(R.id.walkspinner)
        spin.onItemSelectedListener = this
        val spin2 = findViewById<Spinner>(R.id.visitedspinner)
        spin2.onItemSelectedListener = this
        val spin3 = findViewById<Spinner>(R.id.dogsspinner)
        spin3.onItemSelectedListener = this
        val spin4 = findViewById<Spinner>(R.id.fishingspinner)
        spin4.onItemSelectedListener = this
        // Create the instance of ArrayAdapter having the list
        val ad: ArrayAdapter<*> = ArrayAdapter<Any?>(this, android.R.layout.simple_spinner_item, walk)
        val ad2: ArrayAdapter<*> = ArrayAdapter<Any?>(this, android.R.layout.simple_spinner_item, visited)
        val ad3: ArrayAdapter<*> = ArrayAdapter<Any?>(this, android.R.layout.simple_spinner_item, dogs)
        val ad4: ArrayAdapter<*> = ArrayAdapter<Any?>(this, android.R.layout.simple_spinner_item, fishing)
        // set simple layout resource file for each item of spinner
        ad.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item)
        ad2.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item)
        ad3.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item)
        ad4.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item)
        // Set the ArrayAdapter (ad) data on the Spinner which binds data to spinner
        spin.adapter = ad
        spin2.adapter = ad2
        spin3.adapter = ad3
        spin4.adapter = ad4
        //Initialise MainApp.
        app = application as MainApp

        //Editing existing beach
        if (intent.hasExtra("beach_edit")) {
            edit = true
            //Retrieves selected beach.
            beach = intent.extras?.getParcelable("beach_edit")!!
            //Binding correct text to UI
            binding.beachTitle.setText(beach.title)
            binding.description.setText(beach.description)
            binding.size.setText(beach.size)
            binding.walk.text = beach.walk
            binding.visited.text = beach.visited
            binding.dogs.text = beach.dogs
            binding.fishing.text = beach.fishing
            binding.btnAdd.setText(R.string.save_beach)
            //Display image
            Picasso.get()
                .load(beach.image)
                .into(binding.beachImage)
            if (beach.image != Uri.EMPTY) {
                binding.chooseImage.setText(R.string.change_beach_image)
            }
        }

        //Event handling - Add a Beach
        binding.btnAdd.setOnClickListener() {
            beach.title = binding.beachTitle.text.toString()
            beach.description = binding.description.text.toString()
            beach.size = binding.size.text.toString()
            beach.walk = beach.walk
            beach.visited = beach.visited
            beach.dogs = beach.dogs
            beach.fishing = beach.fishing
            //Data validation using Snackbar for message
            if (beach.title.isEmpty()) {
                Snackbar.make(it,R.string.enter_beach_title, Snackbar.LENGTH_LONG).show()
            } else {
                //Using beach.copy to create multiple different beaches to file from MainApp
                if (edit) {
                    app.beaches.update(beach.copy())
                } else {
                    app.beaches.create(beach.copy())
                }
            }
            setResult(RESULT_OK)
            finish()
        }

        //Event handling - Add image
        binding.chooseImage.setOnClickListener {
            showImagePicker(imageIntentLauncher)
        }

        //Event handling - Add location
        binding.beachLocation.setOnClickListener {
            val location = Location(52.245696, -7.139102, 15f)
            if (beach.zoom != 0f) {
                location.lat =  beach.lat
                location.lng = beach.lng
                location.zoom = beach.zoom
            }
            val launcherIntent = Intent(this, MapActivity::class.java)
                .putExtra("location", location)
            mapIntentLauncher.launch(launcherIntent)
        }

        registerImagePickerCallback()
        registerMapCallback()
    }


    override fun onCreateOptionsMenu(menu: Menu): Boolean {
        //Inflate menu
        menuInflater.inflate(R.menu.menu_beach, menu)
        if (edit) menu.getItem(0).isVisible = true
        return super.onCreateOptionsMenu(menu)
    }

    //Handle cancel and delete event
    override fun onOptionsItemSelected(item: MenuItem): Boolean {
        when (item.itemId) {
            R.id.item_delete -> {
                i("Delete button pressed")
                app.beaches.delete(beach)
                finish()
            }
            R.id.item_cancel -> {
                finish()
            }
        }
        return super.onOptionsItemSelected(item)
    }

    //Image Picker
    private fun registerImagePickerCallback() {
        imageIntentLauncher =
            registerForActivityResult(ActivityResultContracts.StartActivityForResult())
            { result ->
                when(result.resultCode){
                    RESULT_OK -> {
                        if (result.data != null) {
                            i("Got Result ${result.data!!.data}")
                            beach.image = result.data!!.data!!
                            //Display image
                            Picasso.get()
                                .load(beach.image)
                                .into(binding.beachImage)
                            binding.chooseImage.setText(R.string.change_beach_image)
                        } // end of if
                    }
                    RESULT_CANCELED -> { } else -> { }
                }
            }
    }

    private fun registerMapCallback() {
        mapIntentLauncher =
            registerForActivityResult(ActivityResultContracts.StartActivityForResult())
            { result ->
                when (result.resultCode) {
                    RESULT_OK -> {
                        if (result.data != null) {
                            i("Got Location ${result.data.toString()}")
                            val location = result.data!!.extras?.getParcelable<Location>("location")!!
                            i("Location == $location")
                            beach.lat = location.lat
                            beach.lng = location.lng
                            beach.zoom = location.zoom
                        } // end of if
                    }
                    RESULT_CANCELED -> { } else -> { }
                }
            }
    }


    override fun onItemSelected(parent: AdapterView<*>?, view: View, position: Int, id: Long) {
        beach.walk = walk[position].toString()
        beach.visited = visited[position].toString()
        beach.dogs = dogs[position].toString()
        beach.fishing = fishing[position].toString()
    }

    override fun onNothingSelected(parent: AdapterView<*>?) {}
}

